const AccountDumy = [
    {
        name:"aaa",
        type: "Type 1",
        invoice: "Invoice 1",
        credits: 10,
        tasks: 5,
        team: "Team A",
        tags: ["Tag1", "Tag2", "Tag3"],
        proposals: 3,
        unread: 2,
        chats: 7,
        pending: true,
        organizer: "Organizer 1"
      },
      {
        name:"bbb",
        type: "Type 2",
        invoice: "Invoice 2",
        credits: 20,
        tasks: 8,
        team: "Team B",
        tags: ["Tag4", "Tag5"],
        proposals: 5,
        unread: 1,
        chats: 10,
        pending: false,
        organizer: "Organizer 2"
      },
      {
        name:"ccc",
        type: "Type 3",
        invoice: "Invoice 3",
        credits: 15,
        tasks: 3,
        team: "Team C",
        tags: ["Tag6", "Tag7", "Tag8"],
        proposals: 2,
        unread: 0,
        chats: 5,
        pending: true,
        organizer: "Organizer 3"
      },
      {
        name:"ddd",
        type: "Type 5",
        invoice: "Invoice 1",
        credits: 10,
        tasks: 5,
        team: "Team A",
        tags: ["Tag1", "Tag2", "Tag3"],
        proposals: 3,
        unread: 2,
        chats: 7,
        pending: true,
        organizer: "Organizer 1"
      },
      {
        name:"eee",
        type: "Type 4",
        invoice: "Invoice 2",
        credits: 20,
        tasks: 8,
        team: "Team B",
        tags: ["Tag4", "Tag5"],
        proposals: 5,
        unread: 1,
        chats: 10,
        pending: false,
        organizer: "Organizer 2"
      },
      {
        name:"fff",
        type: "Type 2",
        invoice: "Invoice 3",
        credits: 15,
        tasks: 3,
        team: "Team C",
        tags: ["Tag6", "Tag7", "Tag8"],
        proposals: 2,
        unread: 0,
        chats: 5,
        pending: true,
        organizer: "Organizer 3"
      },
      {
        name:"aaa",
        type: "Type 3",
        invoice: "Invoice 1",
        credits: 10,
        tasks: 5,
        team: "Team A",
        tags: ["Tag1", "Tag2", "Tag3"],
        proposals: 3,
        unread: 2,
        chats: 7,
        pending: true,
        organizer: "Organizer 1"
      },
      {
        name:"bbb",
        type: "Type 5",
        invoice: "Invoice 2",
        credits: 20,
        tasks: 8,
        team: "Team B",
        tags: ["Tag4", "Tag5"],
        proposals: 5,
        unread: 1,
        chats: 10,
        pending: false,
        organizer: "Organizer 2"
      },
      {
        name:"ddd",
        type: "Type 6",
        invoice: "Invoice 3",
        credits: 15,
        tasks: 3,
        team: "Team C",
        tags: ["Tag6", "Tag7", "Tag8"],
        proposals: 2,
        unread: 0,
        chats: 5,
        pending: true,
        organizer: "Organizer 3"
      }, {
        name:"ccc",
        type: "Type 4",
        invoice: "Invoice 1",
        credits: 10,
        tasks: 5,
        team: "Team A",
        tags: ["Tag1", "Tag2", "Tag3"],
        proposals: 3,
        unread: 2,
        chats: 7,
        pending: true,
        organizer: "Organizer 1"
      },
      {
        name:"eee",
        type: "Type 8",
        invoice: "Invoice 2",
        credits: 20,
        tasks: 8,
        team: "Team B",
        tags: ["Tag4", "Tag5"],
        proposals: 5,
        unread: 1,
        chats: 10,
        pending: false,
        organizer: "Organizer 2"
      },
      {
        name:"fff",
        type: "Type 5",
        invoice: "Invoice 3",
        credits: 15,
        tasks: 3,
        team: "Team C",
        tags: ["Tag6", "Tag7", "Tag8"],
        proposals: 2,
        unread: 0,
        chats: 5,
        pending: true,
        organizer: "Organizer 3"
      }
  ];
  export default AccountDumy;